### PR TITLE
[Server] refactor: exporter interface

### PR DESCRIPTION
**Pull request by jiekun**
### This PR is for:
https://github.com/deepflowio/deepflow/issues/3926

Trying to provide export interface:
```go
type Exporter interface {
	// Start starts an exporter worker
	Start()

	// Put sends data to the exporter worker. Worker could decide what to do next. e.g.:
	// - send it out synchronously.
	// - store it in a queue and handle it later.
	Put(items ...interface{})

	// IsExportData tell the decoder if data need to be sended to specific exporter.
	IsExportData(items interface{}) bool
}
```

And a factory init method for all exporters:
```go
func NewExporters(exportersCfg []ExporterCfg, baseCfg *config.Config) []Exporter
```

### CODE REVIEW

**Comment by jiekun** [comment]
This is a breaking change against previous exporter config. We need an item in CHANGELOG to notify user.
I'm verifying the change and test it on my Kubernetes. This PR is WIP for now.

**Comment by dundun9** [comment]
@jiekun The server check seems to have failed

**Comment by jiekun** [comment]
issue resolved and re-formatted just now.
 /ptal @dundun9 @oilbeater @lzf575

**Comment by jiekun** [comment]
I'm merging the main branch into feature branch, again. please take a look and drop your comment if possible. 
We don't have to waste time running CICD workflow with limited runner resources for those redundant test and check.

**Comment by dundun9** [comment]
@lzf575 Have time to review it as soon as possible

**Comment by lzf575** [comment]
有些配置是公共的， universalTagsManager 也是公共的， 后续需单独提取出来。

**Review by lzf575 — APPROVED** [review]

**Pull request merged**
